name: Run CI checks # The name will show up on the GitHub Actions dashboard

on: [pull_request] # This workflow will run only on Pull Requests

jobs:
  test: # give our job an ID
    runs-on: ubuntu-latest # the image our job will run on
    name: Testing affected apps # the name that will appear on the Actions UI
    steps: # what steps it will perform
      - uses: actions/checkout@v3 # checkout whatever branch the PR is using
      - uses: bahmutov/npm-install@v1 # trigger an `npm install`
      - run: npm run nx affected -- --target=test --base=origin/master --parallel
  build:
    runs-on: ubuntu-latest
    name: Building affected apps
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1
      - run: npm run nx affected -- --target=build --base=origin/master --parallel
  lint:
    runs-on: ubuntu-latest
    name: Building affected apps
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1
      - run: npm run nx affected -- --target=lint --base=origin/master --parallel
  e2e:
    runs-on: ubuntu-latest
    name: Building affected apps
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1
      - run: npm run nx affected -- --target=e2e --base=origin/master --parallel
